import 'package:yboxv2/resource/strings.dart';

class ApiUrl {
  static String login = '${appUrl}api/login';
  static String logout = '${appUrl}api/logout';
  static String register = '${appUrl}api/register';
  static String leader = '${appUrl}api/leader';
  static String adminLeader = '${appUrl}api/admin_leader';
  static String profile = '${appUrl}api/profile';
  static String count = '${appUrl}api/dashboard/count';
  static String amount = '${appUrl}api/dashboard/amount_balance';
  static String album = '${appUrl}api/album_api';
  static String video = '${appUrl}api/video_api';
  static String audio = '${appUrl}api/ringtone_api';
  static String track = '${appUrl}api/track_api';
  static String language = '${appUrl}api/language';
  static String role = '${appUrl}api/roletrack';
  static String publishing = '${appUrl}api/publishing';
  static String country = '${appUrl}api/country';
  static String bank = '${appUrl}api/bank';
  static String info = '${appUrl}api/info';
  static String genre = '${appUrl}api/genre';
  static String labelTransaksi = '${appUrl}api/label_request';
  static String transaksi = '${appUrl}api/transaction_api';
  static String invoice = '${appUrl}api/invoice';
  static String cekReq = '${appUrl}api/cek_request';
  static String akunBank = '${appUrl}api/bank_acc';
  static String akunBankMember = '${appUrl}api/bank_acc_member';
  static String grafikBulanan = '${appUrl}api/dashboard/grafik-bulanan';
  static String aprovedItem = '${appUrl}api/aproved_item';
  static String rejectItem = '${appUrl}api/reject_item';
  static String mssgUuid = '${appUrl}api/mssg_uuid';
  static String mssgMember = '${appUrl}api/mssg_member';
  static String ubahPass = '${appUrl}api/change_password';
  static String tokenFirebase = '${appUrl}api/mssg_token';
  static String publisher = '${appUrl}api/publisher';
  static String platform = '${appUrl}api/platform';
  static String platformProses = '${appUrl}api/platform_process';
  static String sendItem = '${appUrl}api/send_item';
  static String sendNotif = 'https://fcm.googleapis.com/fcm/send';
}
